# Generated by Django 4.2.1 on 2026-05-24 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TagBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TechPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег (км)')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('battery_health', models.IntegerField(blank=True, default=100, null=True, verbose_name='Заряд батареи (%)')),
            ],
            options={
                'verbose_name': 'Технический паспорт',
                'verbose_name_plural': 'Технические паспорта',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Цена за час')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=500, max_digits=6, verbose_name='Цена за день')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес парковки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_available', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Доступен'), (2, 'В аренде'), (3, 'На обслуживании')], default=1, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bikes_photos/%Y/%m/%d/', verbose_name='Фото')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='women.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='bikes', to='women.tagbike', verbose_name='Теги')),
                ('tech_passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='women.techpassport', verbose_name='Техпаспорт')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='women_bike_time_cr_9dee3c_idx')],
            },
        ),
    ]
